### ISSUE TITLE
Unknown android attribute 'SherlockSpinner'

### ISSUE THREAD

**Issue by Sparker0i** [yaxim-org/yaxim#216]
Hi, I am trying to build this app in Android Studio 3.1.2 . The problem is whenever I try to run a gradle sync for this project with the given version of build tools in the build.gradle files, it tells me to update to 25.0.0, and when I do this, I get the error `Unknown android attribute 'SherlockSpinner'` in the Build log.

Now, I do get it that action bar sherlock library is deprecated, so is it necessary that we build this app in a particular version of Android Studio? If yes, then which version?

Thanks.

**Comment by ge0rg** [comment]
I'm using AS 3.0.1 with gradle 3.3 and com.android.tools.build:gradle:2.3.1. Maybe it is just sufficient if you say "no" to the build-tols upgrade?

ABS is deprecated indeed and won't build with newer tools / on newer Android SDK levels. I need to get rid of it and go to appcompat, but this is a major change as well, because you can't have two-line action bars any more, and some other things yaxim relies on.

I'm pretty tired of Google consistently breaking their build tools every some months, so I'm hesitant to upgrade them now, as I don't always have the time to clean up after their changes. Maybe you have better luck with AS 3.0.1 / without AS 3.1.2 changing the project dependencies.

**Comment by Sparker0i** [comment]
That is the problem. AS 3.1 isn't allowing the use of older build tools at all.

But thanks for posting this

**Comment by ge0rg** [comment]
I'll make a last 0.9.x release this month before Google strictens the Google Play submission guidelines. Afterwards, I'm going to *slowly* migrate all the code to recent AS and SDK 26.

**Comment by Sparker0i** [comment]
Cool. Why don't you migrate to SDK 28 itself? That will make your work a lot easier if you are to update your app at this time in the next year.

**Comment by ge0rg** [comment]
I need to replace Sherlock with appcompat, change the UI for material (no subtitle any more) and introduce dynamic permissions. It's a bunch of work I don't have the time for, and it's not even the most important job for yaxim

**Comment by Jacky9425** [comment]
Hello form 2019, I am currently modifying a project that is using ActionBarSherlock. I understand from few sources that the configuration to import the package correctly is by using an older API level and build tools (possibly appcompact too). So does it means its almost impossible for me to import the package correctly now?

I am using latest version of Android Studio and i noticed that they did prompt this `The specified Android SDK Build Tools version (23.0.3) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.2.1.`. So is my assumption that the package is no longer workable with latest Android Studio accurate?

**Comment by ge0rg** [comment]
The current yaxim code base is migrated to appcompat on recent gradle and Android Studio.
